@startuml
skinparam classAttributeIconSize 0
package PasswordSecurityChecker{
    class PasswordSecurityChecker{
    - List<String> name
    - int[] birth
    - List<String> data
    - char[] specials
    - String password
    - String[] commons
    - int tries
    - SimpleDateFormat dateFormat
    - long start
    - long end
    - PasswordSecurityChecker()
    - boolean checkData(String[] args)
    - void loadData(String[] args)
    - void checkEasy()
    - void checkFrequent()
    - void complexCheck()
    - void checkBrute()
    - void tryPassword(List<String> elements)
    - void tryPassword(String s)
    - void tryAllPermutations(List<String> elements)
    - static void displayResult()
    - static void displayHelp()
    }
    
    package bettelini{
        class Paolo
    }
}
PasswordSecurityChecker o-- Paolo : aggregation
@enduml