@startuml "PasswordSecurityChecker"
skinparam classAttributeIconSize 0
class PasswordSecurityChecker{
    - List<String> name
    - int[] birth
    - String info
    - char[] specials
    - String password
    - String[] commons
    - int tries
    - SimpleDateFormat dateFormat
    - PasswordSecurityChecker()
    - void getData(String[] args)
    - void checkEasy()
    - void checkFrequent()
    - void checkComplex()
    - void checkBrute()
    - void tryPassword(List<String> elements)
    - void tryPassword(Strings s)
    - void tryAllPermutations(List<String> elements)
    - static void displayResult()
    - void displayHelp()
}

class utils.ParamHandler

PasswordSecurityChecker o-- utils.ParamHandler : handler
@enduml